services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: django123
    expose:
      - '5432'
    ports:
      - '5434:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'