services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: django123
    ports:
      - '5434:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A assogest worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_HOST=db
      - DB_NAME=django
      - DB_USER=postgres
      - DB_PASSWORD=django123
    volumes:
      - ./tmp/emails:/app/tmp/emails
    depends_on:
      - redis
      - db