# Generated by Django 5.1.4 on 2025-02-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='organization.Membership', to='organization.member'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('member', 'organization')},
        ),
    ]
