# Generated by Django 5.1.4 on 2025-01-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('core', '0002_organization_remove_user_username_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='event_inscriptions', through='agenda.EventInscription', to='agenda.calendarevent'),
        ),
    ]
