# Generated by Django 5.1.4 on 2025-01-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_calendarevent_organization_subscription_event_and_more'),
        ('core', '0003_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='userorganization',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='UserOrganization',
        ),
    ]
