# Generated by Django 5.1.4 on 2025-01-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventinscription',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventinscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='users',
        ),
    ]
