# Generated by Django 5.1.4 on 2025-01-09 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('agenda', '0002_subscription_remove_eventinscription_event_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.calendarevent'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.member'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='members',
            field=models.ManyToManyField(related_name='subscriptions', through='agenda.Subscription',
                                         to='organization.member'),
        ),
    ]
