- name: Ensure www directory exists in home
  file:
    path: /home/debian/www
    state: directory
    mode: '0755'
    owner: debian
    group: debian

- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: debian
    group: debian
  loop:
    - "{{ app_path }}"
    - "{{ app_path }}/tmp"
    - "{{ app_path }}/tmp/emails"
    - "{{ app_path }}/media"
    - "{{ app_path }}/staticfiles"

- name: Copy docker-compose configuration
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_path }}/docker-compose.yml"
    mode: '0644'
  become: false

- name: Create .env file for production
  template:
    src: env.j2
    dest: "{{ app_path }}/.env"
    mode: '0600'
  become: false

- name: Run Django migrations
  community.docker.docker_container_exec:
    container: "{{ project_name }}-web-1"
    command: python manage.py migrate
  register: migration_result
  changed_when: migration_result.stdout != ""

- name: Collect static files
  community.docker.docker_container_exec:
    container: "{{ project_name }}-web-1"
    command: python manage.py collectstatic --noinput
  register: static_result
  changed_when: static_result.stdout != ""