---
- name: Install Nginx and Certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create Nginx configuration
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ project_name }}"
    mode: '0644'
  notify: Restart Nginx

- name: Enable site
  file:
    src: "/etc/nginx/sites-available/{{ project_name }}"
    dest: "/etc/nginx/sites-enabled/{{ project_name }}"
    state: link
  notify: Restart Nginx

- name: Create Nginx cache directory
  file:
    path: /var/cache/nginx
    state: directory
    mode: '0755'

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Obtain SSL certificate
  command: certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos --email your@email.com
  args:
    creates: "/etc/letsencrypt/live/{{ domain_name }}"