---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: no  # On ne met pas à jour le cache ici car déjà fait

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
  notify: reload nginx

- name: Enable site configuration
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link
  notify: reload nginx

- name: Create Nginx cache directory
  file:
    path: /var/cache/nginx
    state: directory
    mode: '0755'

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes